[profile.default]
src = "src"
out = "out"
libs = ["lib", "node_modules"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
evm_version = "Paris"
auto_detect_remappings = false
fs_permissions = [{ access = "read-write", path = "./out" }]
# optimizer = true
# optimizer_runs = 200
# via_ir = true
# optimizer_details = { constantOptimizer = true, yul = true, deduplicate = true }
optimizer = true
optimizer_runs = 200
via_ir = true
optimizer_details = { constantOptimizer = true, yul = true, deduplicate = true }
ignore_warnings = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
